import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { poppins } from "@/lib/font";

import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import MobileNavbar from "@/components/MobileNav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased  `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <section className="py-[10px] fixed w-full z-50">
            <Navbar />
            <MobileNavbar/>
          </section>
          <main className="bg-white  ">{children}</main>

          <section>
            <Footer/>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
