import type { Metadata } from "next";
import "../globals.css";
import { poppins } from "@/lib/font";

import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import MobileNavbar from "@/components/MobileNav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="bg-white">
            <section className="py-[10px] fixed w-full z-50 left-0 ">
              <Navbar />
              <MobileNavbar />
            </section>
            {children}
            <section>
              <Footer />
            </section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
