import type { Metadata } from "next";
import "../globals.css";
import {poppins} from "@/lib/font"

import { ThemeProvider } from "next-themes";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased  `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="bg-white ">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
